packages:
  - "packages/*"
  - "examples/*"

catalog:
  "@playwright/test": 1.61.1
  "@preact/preset-vite": 2.10.5
  "@types/node": 26.0.1
  oxfmt: 0.57.0
  oxlint: 1.72.0
  preact: 10.29.3
  typescript: 6.0.3
  vite: 8.1.2
  vitest: 4.1.9
